import { Fragment, useState } from 'react';
import { BarChart3, ChevronDown, ChevronRight, ExternalLink } from 'lucide-react';
import assessment from '../data/ideAssessment.json';
import practices from '../data/idePractices.json';

const categories = ['Diversidade', 'Gênero', 'Raça'] as const;
const dimensions = [...new Set(assessment.requirements.map(item => item.dimension))];
const normalize = (text: string) => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('pt-BR');
const linkedPractices = new Map(assessment.requirements.map(item => [item.id, practices.practices.filter(practice => practice.requirementIds.includes(item.id))]));
const summaries = categories.map(category => {
  const answers = assessment.requirements.map(item => item.answers[category]).filter(answer => answer !== '—');
  return { category, total: answers.length, yes: answers.filter(answer => answer === 'Sim').length, no: answers.filter(answer => answer === 'Não').length, blank: answers.filter(answer => answer === 'Sem resposta').length };
});
function Answer({ value }: { value: string }) {
  return <span className={`ide-answer ${value === 'Sim' ? 'ide-answer-yes' : value === 'Não' ? 'ide-answer-no' : 'ide-answer-blank'}`}>{value === '—' ? '—' : value}</span>;
}

export function IdeAdherenceSection() {
  const [query, setQuery] = useState('');
  const [dimension, setDimension] = useState('');
  const [category, setCategory] = useState('');
  const [answer, setAnswer] = useState('');
  const [expanded, setExpanded] = useState<Set<number>>(new Set());
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const filtered = assessment.requirements.filter(item => (!dimension || item.dimension === dimension)
    && (!answer || (category ? [item.answers[category as typeof categories[number]]] : Object.values(item.answers)).includes(answer))
    && normalize([item.text, item.dimension, item.theme, ...linkedPractices.get(item.id)!.map(practice => `${practice.title} ${practice.description} ${practice.evidence}`)].join(' ')).includes(normalize(query.trim())));
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const currentPage = Math.min(page, pages);
  const visible = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const total = summaries.reduce((sum, item) => sum + item.total, 0);
  const yes = summaries.reduce((sum, item) => sum + item.yes, 0);
  function toggle(id: number) { setExpanded(previous => { const next = new Set(previous); next.has(id) ? next.delete(id) : next.add(id); return next; }); }
  function selectAnswer(selectedCategory: string, selectedAnswer: string) { setCategory(selectedCategory); setAnswer(selectedAnswer); setPage(1); }

  return <section id="aderencia-ide" className="sp-card mt-6 scroll-mt-44 p-5 sm:p-8" aria-labelledby="adherence-title">
    <div className="mb-5 flex items-start gap-3"><div className="rounded-lg bg-[#F0ECFF] p-3 text-[#5B3DE0]"><BarChart3 aria-hidden="true" className="h-5 w-5" /></div><div><p className="sp-section-label">Rede Equidade · Modelo IDE</p><h2 id="adherence-title" className="mt-1 text-2xl font-bold">Aderência aos requisitos</h2><p className="mt-2 text-sm text-[#5F5A65]">Explore as respostas da autoavaliação e as práticas da Enap relacionadas a cada requisito.</p></div></div>
    <div className="ide-assessment-metrics"><div><strong>{assessment.requirements.length}</strong><span>Requisitos do modelo</span></div><div><strong>{yes}/{total}</strong><span>Respostas “Sim” na planilha</span></div><div><strong>{(yes / total * 100).toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%</strong><span>Respostas “Sim” / avaliações possíveis</span></div><div><strong>{practices.practices.length}</strong><span>Práticas no levantamento</span></div></div>
    <div className="ide-assessment-charts">
      <article className="ide-chart-card"><h3>Autoavaliação por categoria</h3><p>Selecione um segmento para filtrar os requisitos pela resposta.</p><div className="ide-chart-legend"><span><i className="ide-bar-yes" />Sim</span><span><i className="ide-bar-no" />Não</span><span><i className="ide-bar-blank" />Sem resposta</span></div>{summaries.map(item => <div className="ide-chart-row" key={item.category}><div className="flex justify-between gap-2"><strong>{item.category}</strong><span>{item.yes}/{item.total} Sim · {(item.yes / item.total * 100).toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%</span></div><div className="ide-stacked-bar">{([{ value: item.yes, label: 'Sim', className: 'ide-bar-yes' }, { value: item.no, label: 'Não', className: 'ide-bar-no' }, { value: item.blank, label: 'Sem resposta', className: 'ide-bar-blank' }]).filter(segment => segment.value > 0).map(segment => <button key={segment.label} className={segment.className} style={{ width: `${segment.value / item.total * 100}%` }} title={`${item.category}: ${segment.value} ${segment.label}`} aria-label={`Filtrar ${item.category}: ${segment.value} ${segment.label}`} onClick={() => selectAnswer(item.category, segment.label)}>{segment.value}</button>)}</div></div>)}<p className="mt-4">O traço (—) da planilha fica fora do denominador. As células vazias são mantidas como “Sem resposta”.</p></article>
      <article className="ide-chart-card"><h3>Práticas relacionadas por dimensão</h3><p>Uma prática pode estar relacionada a vários requisitos. Selecione uma dimensão para explorar os vínculos.</p>{dimensions.map(item => { const requirements = assessment.requirements.filter(requirement => requirement.dimension === item); const linked = practices.practices.filter(practice => requirements.some(requirement => practice.requirementIds.includes(requirement.id))); const covered = requirements.filter(requirement => linkedPractices.get(requirement.id)!.length > 0).length; return <button className="ide-dimension-chart" key={item} onClick={() => { setDimension(item); setPage(1); }}><strong>{item}</strong><span>{linked.length} práticas distintas · {covered}/{requirements.length} requisitos com vínculos</span><span className="ide-dimension-track"><span style={{ width: `${linked.length / practices.practices.length * 100}%` }} /></span></button>; })}<p className="mt-4">Quantidade de vínculos indica correlação temática; não representa comprovação de atendimento.</p></article>
    </div>
    <div className="ide-assessment-filters"><label className="ide-control"><span>Pesquisar requisitos e práticas</span><input type="search" placeholder="Requisito, prática ou evidência…" value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} /></label><label className="ide-control"><span>Dimensão da aderência</span><select value={dimension} onChange={event => { setDimension(event.target.value); setPage(1); }}><option value="">Todas as dimensões</option>{dimensions.map(item => <option key={item}>{item}</option>)}</select></label><label className="ide-control"><span>Categoria da resposta</span><select value={category} onChange={event => { setCategory(event.target.value); setPage(1); }}><option value="">Qualquer categoria</option>{categories.map(item => <option key={item}>{item}</option>)}</select></label><label className="ide-control"><span>Resposta da autoavaliação</span><select value={answer} onChange={event => { setAnswer(event.target.value); setPage(1); }}><option value="">Todas as respostas</option>{['Sim', 'Não', 'Sem resposta', '—'].map(item => <option key={item}>{item}</option>)}</select></label></div>
    <div className="my-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-[#5F5A65]" role="status">{filtered.length} de 38 requisitos • Expanda uma linha para consultar as práticas relacionadas</p><button className="ide-clear" disabled={!query && !dimension && !category && !answer} onClick={() => { setQuery(''); setDimension(''); setCategory(''); setAnswer(''); setPage(1); }}>Limpar filtros da aderência</button></div>
    <div className="overflow-x-auto rounded-lg border border-[#E1DFE5]"><table className="ide-table ide-assessment-table"><caption className="sr-only">Requisitos da Rede Equidade, respostas da planilha e práticas relacionadas da Enap</caption><thead><tr><th scope="col">ID</th><th scope="col">Requisito</th>{categories.map(item => <th scope="col" key={item}>{item}</th>)}<th scope="col">Práticas</th></tr></thead><tbody>{visible.map(item => { const open = expanded.has(item.id); const related = linkedPractices.get(item.id)!; return <Fragment key={item.id}><tr className={`ide-summary ${open ? 'ide-open' : ''}`} onClick={() => toggle(item.id)}><td>{String(item.id).padStart(2, '0')}</td><th scope="row"><button className="ide-expand" aria-expanded={open} aria-controls={`adherence-detail-${item.id}`} onClick={event => { event.stopPropagation(); toggle(item.id); }}>{open ? <ChevronDown aria-hidden="true" /> : <ChevronRight aria-hidden="true" />}<span>{item.text}</span></button></th>{categories.map(category => <td key={category}><Answer value={item.answers[category]} /></td>)}<td><span className="ide-tag">{related.length}</span></td></tr><tr hidden={!open} id={`adherence-detail-${item.id}`}><td colSpan={6} className="ide-detail-cell">{open && <div className="ide-related"><p className="text-xs text-[#5F5A65]">{item.dimension} · {item.theme}</p><h3 className="mt-2 font-bold">{related.length} práticas relacionadas ao requisito {item.id}</h3>{related.length ? related.map(practice => <article className="ide-related-card" key={practice.id}><h4><span className="ide-tag mr-2">Prática {String(practice.id).padStart(2, '0')}</span>{practice.title}</h4><p><strong>Descrição: </strong>{practice.description}</p><p><strong>Norma/Evidência: </strong>{practice.evidence}</p><div className="ide-note"><strong>Observações: </strong>{practice.mappingNotes}</div><a className="ide-source" href={practice.source} target="_blank" rel="noopener noreferrer">Mais informações<ExternalLink aria-hidden="true" className="h-3.5 w-3.5" /><span className="sr-only"> sobre {practice.title} (nova aba)</span></a></article>) : <p className="mt-3">Nenhuma prática relacionada no levantamento atual. Isso não altera a resposta registrada na planilha.</p>}</div>}</td></tr></Fragment>; })}{!filtered.length && <tr><td colSpan={6} className="py-10 text-center">Nenhum requisito encontrado. Ajuste os filtros.</td></tr>}</tbody></table></div>
    <div className="ide-pagination" aria-label="Paginação de requisitos"><label className="ide-control"><span>Requisitos por página</span><select value={pageSize} onChange={event => { setPageSize(Number(event.target.value)); setPage(1); }}>{[10, 25, 50].map(size => <option key={size}>{size}</option>)}</select></label><span className="text-xs text-[#5F5A65]">{filtered.length ? (currentPage - 1) * pageSize + 1 : 0}–{Math.min(currentPage * pageSize, filtered.length)} de {filtered.length} · Página {currentPage} de {pages}</span><div className="flex gap-2"><button className="ide-clear" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Anterior</button><button className="ide-clear" disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)}>Próxima</button></div></div>
    <p className="mt-4 text-xs leading-relaxed text-[#6F6B75]">Fonte da autoavaliação: {assessment.source}. Os gráficos reproduzem as respostas informadas e não constituem validação independente. Consulte as observações e a evidência de cada prática.</p>
  </section>;
}
